//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class AMP_STATUS
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static AMP_STATUS AMP_ON = new AMP_STATUS("AMP_ON");
  
  public final static AMP_STATUS AMP_OFF = new AMP_STATUS("AMP_OFF");
  
  private static AMP_STATUS[] swigValues = { AMP_ON, AMP_OFF };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [cf862993-e036-47bd-81c8-39f610151594] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [14e500f9-1f41-4fb9-ad80-4b9702d98bad] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static AMP_STATUS swigToEnum(int swigValue)
  {
  // ## OperationBody [907c6b9a-edcd-4412-99a9-de567db0665f] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + AMP_STATUS.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private AMP_STATUS(String swigName)
  {
  // ## OperationBody [c6b2e553-febe-4e02-b29d-d3c278c988cf] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private AMP_STATUS(String swigName,
    int swigValue)
  {
  // ## OperationBody [8c96b286-a260-47e9-bb72-777821967452] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private AMP_STATUS(String swigName,
    AMP_STATUS swigEnum)
  {
  // ## OperationBody [190c632c-c3ab-4fd1-895c-12c8ec2e0f4d] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
