//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class AMPLI_CHANNEL
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static AMPLI_CHANNEL AMP_NO_CHANNEL = new AMPLI_CHANNEL("AMP_NO_CHANNEL");
  
  public final static AMPLI_CHANNEL AMP_FRONT_CHANNEL = new AMPLI_CHANNEL("AMP_FRONT_CHANNEL");
  
  public final static AMPLI_CHANNEL AMP_REAR_CHANNEL = new AMPLI_CHANNEL("AMP_REAR_CHANNEL");
  
  public final static AMPLI_CHANNEL AMP_END_CHANNEL = new AMPLI_CHANNEL("AMP_END_CHANNEL");
  
  private static AMPLI_CHANNEL[] swigValues = { AMP_NO_CHANNEL, AMP_FRONT_CHANNEL, AMP_REAR_CHANNEL, AMP_END_CHANNEL };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [532c9b48-48a9-4824-b25a-37283cc97750] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [3fba6b51-d663-46c3-8206-0f69203f13aa] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static AMPLI_CHANNEL swigToEnum(int swigValue)
  {
  // ## OperationBody [b54b27f8-7a80-41aa-872a-bb3b8251aaa1] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + AMPLI_CHANNEL.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private AMPLI_CHANNEL(String swigName)
  {
  // ## OperationBody [cc5e5a09-2145-4ab4-89d0-fc4551a8d5c7] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private AMPLI_CHANNEL(String swigName,
    int swigValue)
  {
  // ## OperationBody [5bdd15d0-0a4b-43cb-8c1d-7097dac66eaf] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private AMPLI_CHANNEL(String swigName,
    AMPLI_CHANNEL swigEnum)
  {
  // ## OperationBody [ec4a66c9-ebe9-4ef6-8cc5-65ecc6f5e4d7] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
