//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class DIRANA_ALIGNMENT_TYPE
{
  // Attributes
  
  private long swigCPtr;
  
  protected boolean swigCMemOwn;
  
  // Operations
  
  protected DIRANA_ALIGNMENT_TYPE(long cPtr,
    boolean cMemoryOwn)
  {
  // ## OperationBody [334a0439-6051-4f0e-94e3-9971de7a8f96] 
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(DIRANA_ALIGNMENT_TYPE obj)
  {
  // ## OperationBody [a60e4ec5-9511-470c-b71c-3f28d44c60ed] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }
  
  protected void finalize()
  {
  // ## OperationBody [800a270f-3a28-46c7-a554-20463f074cd2] 
      delete();
  // ## OperationBody End 
  }
  
  public synchronized void delete()
  {
  // ## OperationBody [007bc5a1-7190-4cef-ad1e-528a77c1f1b2] 
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dspJNI.delete_DIRANA_ALIGNMENT_TYPE(swigCPtr);
        }
        swigCPtr = 0;
      }
  // ## OperationBody End 
  }
  
  public void setFM_IF_Filter_Center_Freq_Main_tuner(int value)
  {
  // ## OperationBody [e6ae8e3f-7378-40b6-9baa-2106afcef460] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Main_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_IF_Filter_Center_Freq_Main_tuner()
  {
  // ## OperationBody [5bd84879-98e8-48b4-8cea-87781ec5ae19] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Main_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setAM_IF_Filter_Center_Freq_Main_tuner(int value)
  {
  // ## OperationBody [7a5ca77d-f4ba-488b-adab-9663960106c1] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Main_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getAM_IF_Filter_Center_Freq_Main_tuner()
  {
  // ## OperationBody [eaff7002-b045-4d73-b092-05f7b851de53] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Main_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_IF_Filter_Center_Freq_Sub_tuner(int value)
  {
  // ## OperationBody [2c2bb0f7-eaf0-4aeb-ac84-211ee7834cae] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Sub_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_IF_Filter_Center_Freq_Sub_tuner()
  {
  // ## OperationBody [240162e1-1213-4dcf-bdf2-405ceb407ff1] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Sub_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setAM_IF_Filter_Center_Freq_Sub_tuner(int value)
  {
  // ## OperationBody [980d0e2d-c643-488f-acc1-c2dd231021d6] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Sub_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getAM_IF_Filter_Center_Freq_Sub_tuner()
  {
  // ## OperationBody [39fa0372-109a-417c-ad75-4b8d53158fca] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Sub_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Offset_Main_tuner_Europe_H(int value)
  {
  // ## OperationBody [b089b288-5424-4b42-969d-31dc27e778a0] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_H_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Offset_Main_tuner_Europe_H()
  {
  // ## OperationBody [5d0c6205-310b-4346-b92b-da87b0d29473] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_H_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Offset_Main_tuner_Europe_L(int value)
  {
  // ## OperationBody [006afd60-c156-417a-9640-53dde09b57ba] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_L_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Offset_Main_tuner_Europe_L()
  {
  // ## OperationBody [b1a5d673-e650-4656-8405-7a863ca5c775] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_L_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Offset_Main_tuner_Japan_H(int value)
  {
  // ## OperationBody [cb733f1b-4576-4de3-a0bf-b342de489fef] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_H_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Offset_Main_tuner_Japan_H()
  {
  // ## OperationBody [fd048534-71fa-436d-9779-405c787eaa5a] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_H_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Offset_Main_tuner_Japan_L(int value)
  {
  // ## OperationBody [5675d8b2-487f-48f1-8b40-284a5640a0ad] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_L_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Offset_Main_tuner_Japan_L()
  {
  // ## OperationBody [297c30a5-7b66-4a04-938b-b608a8de4878] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_L_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Offset_tuner_Europe_H(int value)
  {
  // ## OperationBody [703282b8-1ef2-483b-9a96-752558d9a200] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_H_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Offset_tuner_Europe_H()
  {
  // ## OperationBody [9d706d0a-38d0-499b-a61a-8966327cf23d] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_H_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Offset_tuner_Europe_L(int value)
  {
  // ## OperationBody [3b908c04-a891-443a-8847-7047199c0924] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_L_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Offset_tuner_Europe_L()
  {
  // ## OperationBody [d956c85a-b780-45a2-b012-8ac25c1db8a0] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_L_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setKW_Offset_tuner_H(int value)
  {
  // ## OperationBody [42c348b1-7fce-44eb-8962-cd7e1843a227] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_H_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getKW_Offset_tuner_H()
  {
  // ## OperationBody [a91b7f4d-6cba-4bf1-b3e0-e1bc00fdba37] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_H_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setKW_Offset_tuner_L(int value)
  {
  // ## OperationBody [67b4be0c-7c82-4ff1-99ac-d4c4bf0d0509] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_L_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getKW_Offset_tuner_L()
  {
  // ## OperationBody [14684b50-99e9-4d77-8a4e-6fa04e419c12] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_L_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Offset_tuner_USA_H(int value)
  {
  // ## OperationBody [58fd7b34-d0db-4c8e-bfa8-bf79f22ce8c1] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_H_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Offset_tuner_USA_H()
  {
  // ## OperationBody [5f363da2-742c-40e3-96c8-7a915c29274b] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_H_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Offset_tuner_USA_L(int value)
  {
  // ## OperationBody [219e072f-3766-4155-a9ad-93ee6cbd9e73] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_L_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Offset_tuner_USA_L()
  {
  // ## OperationBody [8e7b7eaa-11e4-4b10-8881-526cc9510a07] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_L_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Level_Main_tuner(int value)
  {
  // ## OperationBody [e0a81cf9-7748-41bd-8bfc-c1a2e3dc3668] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Level_Main_tuner()
  {
  // ## OperationBody [235d211a-f8b5-4018-9acc-d826e48fc19c] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Level_Sub_tuner(int value)
  {
  // ## OperationBody [5a4ddcc6-bd20-4857-9787-4b9a921be019] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Level_Sub_tuner()
  {
  // ## OperationBody [7a5f242b-4323-40ba-bd31-8b1e07bfe6bd] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Level_Main_tuner_Japan(int value)
  {
  // ## OperationBody [f40d5267-6cb8-468a-a071-94755e6b85c0] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_Japan_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Level_Main_tuner_Japan()
  {
  // ## OperationBody [c0d39d4b-5234-480d-8440-d14a3c159a76] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_Japan_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Level_Sub_tuner_Japan(int value)
  {
  // ## OperationBody [21b4c818-66c7-4566-809a-0eee8f9265c3] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_Japan_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Level_Sub_tuner_Japan()
  {
  // ## OperationBody [c8f95687-7200-4405-867a-5f5f806ca0db] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_Japan_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Level_Main_tuner(int value)
  {
  // ## OperationBody [269ca0a7-73ed-4971-964b-6959a2d3ab02] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Level_Main_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Level_Main_tuner()
  {
  // ## OperationBody [e83a3d61-fb6a-46c8-b1fe-49e793471bae] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Level_Main_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setMW_Level_Sub_tuner(int value)
  {
  // ## OperationBody [4f74a6d4-d2fc-4735-b040-8711bcc3616c] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Level_Sub_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getMW_Level_Sub_tuner()
  {
  // ## OperationBody [6b3e2339-ee12-40a0-b8b4-1cbff734113c] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_MW_Level_Sub_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setKW_Level_Main_tuner(int value)
  {
  // ## OperationBody [76b6ee1c-3a35-432a-8f46-dfd9a0f8c2d7] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Level_Main_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getKW_Level_Main_tuner()
  {
  // ## OperationBody [2f7d74a5-8d23-4c44-ae6e-bf928579fd88] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Level_Main_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setKW_Level_Sub_tuner(int value)
  {
  // ## OperationBody [3b92a9f4-f8e3-48a6-9cd6-ec056b382388] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Level_Sub_tuner_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getKW_Level_Sub_tuner()
  {
  // ## OperationBody [285df1f5-8f9c-4bc9-917c-d718095511a0] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_KW_Level_Sub_tuner_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setFM_Stereo_decoder(int value)
  {
  // ## OperationBody [7e0de5f6-0444-4964-a348-b5e29b92ac11] 
      dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Stereo_decoder_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getFM_Stereo_decoder()
  {
  // ## OperationBody [879216f9-0bfe-4d76-9dab-7f676a8e346e] 
      return dspJNI.DIRANA_ALIGNMENT_TYPE_FM_Stereo_decoder_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public DIRANA_ALIGNMENT_TYPE()
  {
  // ## OperationBody [bb3ad8d9-6c75-4f92-bb6b-0db851c2fc09] 
      this(dspJNI.new_DIRANA_ALIGNMENT_TYPE(), true);
  // ## OperationBody End 
  }

}
