//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class DR_AUDIO_SOURCES_TYPES
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_NO_SOURCE = new DR_AUDIO_SOURCES_TYPES("SRC_NO_SOURCE");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_TUNER = new DR_AUDIO_SOURCES_TYPES("SRC_TUNER");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_CD = new DR_AUDIO_SOURCES_TYPES("SRC_CD");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_MP3 = new DR_AUDIO_SOURCES_TYPES("SRC_MP3");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_CDC = new DR_AUDIO_SOURCES_TYPES("SRC_CDC");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_AUX = new DR_AUDIO_SOURCES_TYPES("SRC_AUX");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_PHONE = new DR_AUDIO_SOURCES_TYPES("SRC_PHONE");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_TTS = new DR_AUDIO_SOURCES_TYPES("SRC_TTS");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_TA_PTY = new DR_AUDIO_SOURCES_TYPES("SRC_TA_PTY");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_TTS_ON_AUX = new DR_AUDIO_SOURCES_TYPES("SRC_TTS_ON_AUX");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_AUX_CONVERGENCE = new DR_AUDIO_SOURCES_TYPES("SRC_AUX_CONVERGENCE");
  
  public final static DR_AUDIO_SOURCES_TYPES SRC_MAX_AUDIO_SOURCES = new DR_AUDIO_SOURCES_TYPES("SRC_MAX_AUDIO_SOURCES");
  
  private static DR_AUDIO_SOURCES_TYPES[] swigValues = { SRC_NO_SOURCE, SRC_TUNER, SRC_CD, SRC_MP3, SRC_CDC, SRC_AUX, SRC_PHONE, SRC_TTS, SRC_TA_PTY, SRC_TTS_ON_AUX, SRC_AUX_CONVERGENCE, SRC_MAX_AUDIO_SOURCES };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [bd441e0c-6c58-42a8-aa73-57fd54982b24] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [a6e83256-7f3f-43f2-9fef-bf7f0eefe8b9] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static DR_AUDIO_SOURCES_TYPES swigToEnum(int swigValue)
  {
  // ## OperationBody [18b0df8f-19ad-4c15-b8f8-698739d90031] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + DR_AUDIO_SOURCES_TYPES.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private DR_AUDIO_SOURCES_TYPES(String swigName)
  {
  // ## OperationBody [55c4e29e-c651-4c78-8ff1-8514258b71d0] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private DR_AUDIO_SOURCES_TYPES(String swigName,
    int swigValue)
  {
  // ## OperationBody [10922466-2187-4a14-81fe-b95a58663aa1] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private DR_AUDIO_SOURCES_TYPES(String swigName,
    DR_AUDIO_SOURCES_TYPES swigEnum)
  {
  // ## OperationBody [62a0bed3-0d4d-488a-84c8-62bb9b2e9b09] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
