//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class dsp
  implements dspConstants
{
  // Operations
  
  public static void setG_current_volume(int value)
  {
  // ## OperationBody [ae54ebb5-5ddf-4564-8d8a-7b3496de8795] 
      dspJNI.g_current_volume_set(value);
  // ## OperationBody End 
  }
  
  public static int getG_current_volume()
  {
  // ## OperationBody [0464b1ab-4f37-4e39-994f-785ded534568] 
      return dspJNI.g_current_volume_get();
  // ## OperationBody End 
  }
  
  public static STATUS initDirana()
  {
  // ## OperationBody [7e3475bc-3e87-471b-89d7-fc8909a313c7] 
      return STATUS.swigToEnum(dspJNI.initDirana());
  // ## OperationBody End 
  }
  
  public static STATUS setSource(DR_AUDIO_SOURCES_TYPES p_source)
  {
  // ## OperationBody [3e855e39-0d39-4715-9fb5-ee0436b9ba84] 
      return STATUS.swigToEnum(dspJNI.setSource(p_source.swigValue()));
  // ## OperationBody End 
  }
  
  public static STATUS getSource(SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES p_source)
  {
  // ## OperationBody [273f9bf7-6a49-48c9-a2ba-7a821ae30be5] 
      return STATUS.swigToEnum(dspJNI.getSource(SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES.getCPtr(p_source)));
  // ## OperationBody End 
  }
  
  public static STATUS setVolume(int p_volume)
  {
  // ## OperationBody [db2e62f0-a6d4-4a1f-a803-f7f2fd4efd81] 
      return STATUS.swigToEnum(dspJNI.setVolume(p_volume));
  // ## OperationBody End 
  }
  
  public static STATUS getVolume(SWIGTYPE_p_int p_volume)
  {
  // ## OperationBody [932d949e-775f-470e-b8d5-5e32dc5b09fa] 
      return STATUS.swigToEnum(dspJNI.getVolume(SWIGTYPE_p_int.getCPtr(p_volume)));
  // ## OperationBody End 
  }
  
  public static STATUS setChannelGain(AMPLI_CHANNEL p_channel,
    AMPLI_GAINS p_gain)
  {
  // ## OperationBody [4e3cf8e0-71c9-4935-87f9-0157e9a8a3ae] 
      return STATUS.swigToEnum(dspJNI.setChannelGain(p_channel.swigValue(), p_gain.swigValue()));
  // ## OperationBody End 
  }
  
  public static STATUS getChannelGain(AMPLI_CHANNEL p_channel,
    SWIGTYPE_p_AMPLI_GAINS p_gain)
  {
  // ## OperationBody [cf55fd33-e637-40d1-a42b-f32723f10f9e] 
      return STATUS.swigToEnum(dspJNI.getChannelGain(p_channel.swigValue(), SWIGTYPE_p_AMPLI_GAINS.getCPtr(p_gain)));
  // ## OperationBody End 
  }
  
  public static STATUS playSin(int p_volume)
  {
  // ## OperationBody [175819ee-245f-45e0-ad5e-b97e1a5a0af4] 
      return STATUS.swigToEnum(dspJNI.playSin(p_volume));
  // ## OperationBody End 
  }
  
  public static STATUS doMute()
  {
  // ## OperationBody [57559d65-bf5b-402a-95e5-f0a30f0991b0] 
      return STATUS.swigToEnum(dspJNI.doMute());
  // ## OperationBody End 
  }
  
  public static STATUS doDeMute()
  {
  // ## OperationBody [30e0789f-152f-487f-9370-90030e84d86a] 
      return STATUS.swigToEnum(dspJNI.doDeMute());
  // ## OperationBody End 
  }
  
  public static STATUS change_band(TYPE_BAND p_new_band)
  {
  // ## OperationBody [8045b978-a0fb-489c-bd17-2529ad391dd9] 
      return STATUS.swigToEnum(dspJNI.change_band(p_new_band.swigValue()));
  // ## OperationBody End 
  }
  
  public static void get_band(TYPE_BAND p_band,
    TYPE_SUB_BAND p_subband)
  {
  // ## OperationBody [358da557-996a-4d20-bfd9-389c46962268] 
      dspJNI.get_band(p_band.swigValue(), p_subband.swigValue());
  // ## OperationBody End 
  }
  
  public static STATUS set_frequency(int p_frequency,
    TYPE_BAND p_band,
    TYPE_SUB_BAND p_subAM_band)
  {
  // ## OperationBody [00dc1899-ec01-4413-853a-4606dae45137] 
      return STATUS.swigToEnum(dspJNI.set_frequency(p_frequency, p_band.swigValue(), p_subAM_band.swigValue()));
  // ## OperationBody End 
  }
  
  public static int get_frequency()
  {
  // ## OperationBody [e88f076f-bb9d-448d-8981-9b064f8947f9] 
      return dspJNI.get_frequency();
  // ## OperationBody End 
  }
  
  public static STATUS set_LeafDiceCfg(int p_freq,
    TYPE_BAND p_band,
    TYPE_SUB_BAND p_subAM_band)
  {
  // ## OperationBody [bf896fd1-f0fd-4446-a28f-f4b4c1f04319] 
      return STATUS.swigToEnum(dspJNI.set_LeafDiceCfg(p_freq, p_band.swigValue(), p_subAM_band.swigValue()));
  // ## OperationBody End 
  }
  
  public static STATUS get_Freq_Band_fromTuner(SWIGTYPE_p_int p_freq,
    SWIGTYPE_p_TYPE_BAND p_band,
    SWIGTYPE_p_TYPE_SUB_BAND p_subband)
  {
  // ## OperationBody [7dcb42e8-2da9-4c9a-beb9-451dde91b3e0] 
      return STATUS.swigToEnum(dspJNI.get_Freq_Band_fromTuner(SWIGTYPE_p_int.getCPtr(p_freq), SWIGTYPE_p_TYPE_BAND.getCPtr(p_band), SWIGTYPE_p_TYPE_SUB_BAND.getCPtr(p_subband)));
  // ## OperationBody End 
  }
  
  public static STATUS setSourceAUX()
  {
  // ## OperationBody [e9e7bdde-215a-4c90-a06f-e86e2853c5b0] 
      return STATUS.swigToEnum(dspJNI.setSourceAUX());
  // ## OperationBody End 
  }
  
  public static STATUS SetAuxOnPrimaryStereo()
  {
  // ## OperationBody [930f615a-ef3c-4218-bd27-3adacbce99c9] 
      return STATUS.swigToEnum(dspJNI.SetAuxOnPrimaryStereo());
  // ## OperationBody End 
  }
  
  public static STATUS SetTunerOnPrimaryStereo()
  {
  // ## OperationBody [85b1c40a-2656-4524-893f-4926e96d01db] 
      return STATUS.swigToEnum(dspJNI.SetTunerOnPrimaryStereo());
  // ## OperationBody End 
  }
  
  public static STATUS SetI2SOnPrimaryStereo()
  {
  // ## OperationBody [39294620-6926-4e53-94ec-911dcbd7ecec] 
      return STATUS.swigToEnum(dspJNI.SetI2SOnPrimaryStereo());
  // ## OperationBody End 
  }
  
  public static STATUS SetCdcOnPrimaryStereo()
  {
  // ## OperationBody [cbac3520-542b-4f28-87bf-e96953ba6212] 
      return STATUS.swigToEnum(dspJNI.SetCdcOnPrimaryStereo());
  // ## OperationBody End 
  }
  
  public static STATUS SetPhoneOnPrimaryStereo()
  {
  // ## OperationBody [b7d4e9e5-f6ca-4980-9619-64fcc8b413e2] 
      return STATUS.swigToEnum(dspJNI.SetPhoneOnPrimaryStereo());
  // ## OperationBody End 
  }

}
