//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public interface dspConstants
{
  // Attributes
  
  int VOLUMEINDBTABLE = dspJNI.VOLUMEINDBTABLE_get();
  
  int MAXVOLSTEP = dspJNI.MAXVOLSTEP_get();

}
