//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class dspJNI
{
  // Operations
  
  public native final static void USUC_us_set(long jarg1,
    USUC jarg1_,
    int jarg2);
  
  public native final static int USUC_us_get(long jarg1,
    USUC jarg1_);
  
  public native final static void USUC_uc_set(long jarg1,
    USUC jarg1_,
    long jarg2);
  
  public native final static long USUC_uc_get(long jarg1,
    USUC jarg1_);
  
  public native final static long new_USUC();
  
  public native final static void delete_USUC(long jarg1);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Main_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Main_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Main_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Main_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Sub_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_IF_Filter_Center_Freq_Sub_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Sub_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_AM_IF_Filter_Center_Freq_Sub_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_H_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_H_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_L_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Europe_L_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_H_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_H_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_L_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Offset_Main_tuner_Japan_L_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_H_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_H_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_L_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_Europe_L_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_H_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_H_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_L_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_KW_Offset_tuner_L_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_H_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_H_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_L_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Offset_tuner_USA_L_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_Japan_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Level_Main_tuner_Japan_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_Japan_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Level_Sub_tuner_Japan_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Level_Main_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Level_Main_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_MW_Level_Sub_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_MW_Level_Sub_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_KW_Level_Main_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_KW_Level_Main_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_KW_Level_Sub_tuner_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_KW_Level_Sub_tuner_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static void DIRANA_ALIGNMENT_TYPE_FM_Stereo_decoder_set(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_,
    int jarg2);
  
  public native final static int DIRANA_ALIGNMENT_TYPE_FM_Stereo_decoder_get(long jarg1,
    DIRANA_ALIGNMENT_TYPE jarg1_);
  
  public native final static long new_DIRANA_ALIGNMENT_TYPE();
  
  public native final static void delete_DIRANA_ALIGNMENT_TYPE(long jarg1);
  
  public native final static void g_current_volume_set(int jarg1);
  
  public native final static int g_current_volume_get();
  
  public native final static int VOLUMEINDBTABLE_get();
  
  public native final static int MAXVOLSTEP_get();
  
  public native final static int initDirana();
  
  public native final static int setSource(int jarg1);
  
  public native final static int getSource(long jarg1);
  
  public native final static int setVolume(int jarg1);
  
  public native final static int getVolume(long jarg1);
  
  public native final static int setChannelGain(int jarg1,
    int jarg2);
  
  public native final static int getChannelGain(int jarg1,
    long jarg2);
  
  public native final static int playSin(int jarg1);
  
  public native final static int doMute();
  
  public native final static int doDeMute();
  
  public native final static int change_band(int jarg1);
  
  public native final static void get_band(int jarg1,
    int jarg2);
  
  public native final static int set_frequency(int jarg1,
    int jarg2,
    int jarg3);
  
  public native final static int get_frequency();
  
  public native final static int set_LeafDiceCfg(int jarg1,
    int jarg2,
    int jarg3);
  
  public native final static int get_Freq_Band_fromTuner(long jarg1,
    long jarg2,
    long jarg3);
  
  public native final static int setSourceAUX();
  
  public native final static int SetAuxOnPrimaryStereo();
  
  public native final static int SetTunerOnPrimaryStereo();
  
  public native final static int SetI2SOnPrimaryStereo();
  
  public native final static int SetCdcOnPrimaryStereo();
  
  public native final static int SetPhoneOnPrimaryStereo();

}
