//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class STATUS
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static STATUS ERROR = new STATUS("ERROR");
  
  public final static STATUS OK = new STATUS("OK");
  
  private static STATUS[] swigValues = { ERROR, OK };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [4b6de72f-f2cb-431e-8eca-cc56e8e2d5b3] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [62ae419a-27f1-4c38-abbe-9c24e983be18] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static STATUS swigToEnum(int swigValue)
  {
  // ## OperationBody [0bd79963-c0d9-4bf7-94d1-a608555039df] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + STATUS.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private STATUS(String swigName)
  {
  // ## OperationBody [4ba54867-d8af-40db-82b3-229a83b8f852] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private STATUS(String swigName,
    int swigValue)
  {
  // ## OperationBody [b1f3a7d6-e587-4a8d-bc24-47734c69d020] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private STATUS(String swigName,
    STATUS swigEnum)
  {
  // ## OperationBody [55516ee7-ba73-40e3-aee7-d9f7b0ab5d6a] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
