//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_AMPLI_GAINS
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_AMPLI_GAINS(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [08cba8b5-375d-4773-a235-267c2e0d5187] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_AMPLI_GAINS()
  {
  // ## OperationBody [a18170a4-37fd-4a1e-be3a-00933852334f] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_AMPLI_GAINS obj)
  {
  // ## OperationBody [9b523525-f155-48c6-994e-42ef40407b89] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
