//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_int
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_int(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [4a64346f-0528-4390-bd71-e3198639abae] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_int()
  {
  // ## OperationBody [6d7441e8-2496-430c-8299-1ae8163f4cff] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_int obj)
  {
  // ## OperationBody [e2b974d7-056f-4fda-8dc5-f99247a79700] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
