//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_TYPE_BAND
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_TYPE_BAND(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [241986d2-1530-42cc-a58e-6ac853ea18fd] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_TYPE_BAND()
  {
  // ## OperationBody [a5646b29-b20d-4a17-93c9-d3b5e2a5fc31] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_TYPE_BAND obj)
  {
  // ## OperationBody [2de176ef-8915-4ae2-8ecd-6b270f85dd6f] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
