//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_unsigned_char
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_unsigned_char(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [a95730fb-2afd-4c7e-9de5-3cab5374a2ad] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_unsigned_char()
  {
  // ## OperationBody [78059fcb-d1d8-4909-86e4-1b73808c413a] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_unsigned_char obj)
  {
  // ## OperationBody [92398e00-21e6-494e-a4c5-6082df5888d4] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
