//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_TYPE_SUB_BAND
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_TYPE_SUB_BAND(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [71e07ae2-f85d-4088-9f41-95c4d219eb18] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_TYPE_SUB_BAND()
  {
  // ## OperationBody [14cdb34f-d724-4de6-b2f1-23e0a904ee6b] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_TYPE_SUB_BAND obj)
  {
  // ## OperationBody [1ba8a370-087f-49d9-ad40-b9c03043a394] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
