//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES
{
  // Attributes
  
  private long swigCPtr;
  
  // Operations
  
  protected SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES(long cPtr,
    boolean futureUse)
  {
  // ## OperationBody [1cf068f0-8fd5-4975-a0c2-50c05722835e] 
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES()
  {
  // ## OperationBody [37710874-2de9-43c0-98cb-4f24b6618186] 
      swigCPtr = 0;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(SWIGTYPE_p_DR_AUDIO_SOURCES_TYPES obj)
  {
  // ## OperationBody [fc421c92-1337-4638-bfd0-8087492bdaed] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }

}
