//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class TYPE_SUB_BAND
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static TYPE_SUB_BAND AM_MW_BAND = new TYPE_SUB_BAND("AM_MW_BAND");
  
  public final static TYPE_SUB_BAND AM_KW_BAND = new TYPE_SUB_BAND("AM_KW_BAND");
  
  private static TYPE_SUB_BAND[] swigValues = { AM_MW_BAND, AM_KW_BAND };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [74dbefe2-baf7-4d15-8ac4-d4fcda8c1471] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [32b3b885-e44a-4222-b406-66609a430e45] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static TYPE_SUB_BAND swigToEnum(int swigValue)
  {
  // ## OperationBody [34aebc14-ba70-41f3-ad17-46f8526fa6e1] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + TYPE_SUB_BAND.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private TYPE_SUB_BAND(String swigName)
  {
  // ## OperationBody [f26df228-9d3e-4cd8-8e51-69be05b1cf25] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private TYPE_SUB_BAND(String swigName,
    int swigValue)
  {
  // ## OperationBody [31f64468-2848-4a10-8a59-37f03ce8e4af] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private TYPE_SUB_BAND(String swigName,
    TYPE_SUB_BAND swigEnum)
  {
  // ## OperationBody [b46fb983-7414-4c8f-b0ac-d3503841cb01] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
