//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public final class TYPE_BAND
{
  // Attributes
  
  private static int swigNext = 0;
  
  private final int swigValue;
  
  private final String swigName;
  
  // Roles
  
  public final static TYPE_BAND FM_BAND = new TYPE_BAND("FM_BAND");
  
  public final static TYPE_BAND AM_BAND = new TYPE_BAND("AM_BAND");
  
  private static TYPE_BAND[] swigValues = { FM_BAND, AM_BAND };
  
  // Operations
  
  public final int swigValue()
  {
  // ## OperationBody [786b9be2-c61c-4f1e-b04a-1304976bf478] 
      return swigValue;
  // ## OperationBody End 
  }
  
  public String toString()
  {
  // ## OperationBody [1f2682c8-525a-4589-a810-d7777a6d58bc] 
      return swigName;
  // ## OperationBody End 
  }
  
  public static TYPE_BAND swigToEnum(int swigValue)
  {
  // ## OperationBody [d0c8a29f-2d66-4637-ad5a-5be226871200] 
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + TYPE_BAND.class + " with value " + swigValue);
  // ## OperationBody End 
  }
  
  private TYPE_BAND(String swigName)
  {
  // ## OperationBody [a026bbca-c481-44ab-8787-c49b2ab69104] 
      this.swigName = swigName;
      this.swigValue = swigNext++;
  // ## OperationBody End 
  }
  
  private TYPE_BAND(String swigName,
    int swigValue)
  {
  // ## OperationBody [0f2a74f6-7bfd-4e39-9d1b-4e58078eb433] 
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
  // ## OperationBody End 
  }
  
  private TYPE_BAND(String swigName,
    TYPE_BAND swigEnum)
  {
  // ## OperationBody [1f2847d0-fb65-40b2-a777-519e6473de76] 
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
  // ## OperationBody End 
  }

}
