//  ----------------------------------------------------------------------------
//  * This file was automatically generated by SWIG (http://www.swig.org).
//  * Version 2.0.9
//  *
//  * Do not make changes to this file unless you know what you are doing--modify
//  * the SWIG interface file instead.
//  * -----------------------------------------------------------------------------

public class USUC
{
  // Attributes
  
  private long swigCPtr;
  
  protected boolean swigCMemOwn;
  
  // Operations
  
  protected USUC(long cPtr,
    boolean cMemoryOwn)
  {
  // ## OperationBody [534920f7-2fa6-4d41-b852-18871ba5f17b] 
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
  // ## OperationBody End 
  }
  
  protected static long getCPtr(USUC obj)
  {
  // ## OperationBody [b8b34fe6-a34b-4549-b4a1-2d74ed41abe1] 
      return (obj == null) ? 0 : obj.swigCPtr;
  // ## OperationBody End 
  }
  
  protected void finalize()
  {
  // ## OperationBody [60fdad27-9173-48e8-a633-1623c3fd4f13] 
      delete();
  // ## OperationBody End 
  }
  
  public synchronized void delete()
  {
  // ## OperationBody [af32f868-b968-4df0-bf68-9ac04e6838a2] 
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dspJNI.delete_USUC(swigCPtr);
        }
        swigCPtr = 0;
      }
  // ## OperationBody End 
  }
  
  public void setUs(int value)
  {
  // ## OperationBody [e8909d78-9085-43e7-ad7e-010a074d6773] 
      dspJNI.USUC_us_set(swigCPtr, this, value);
  // ## OperationBody End 
  }
  
  public int getUs()
  {
  // ## OperationBody [2c87f9fd-3fbd-49fe-9f7a-3a3657a3d30b] 
      return dspJNI.USUC_us_get(swigCPtr, this);
  // ## OperationBody End 
  }
  
  public void setUc(SWIGTYPE_p_unsigned_char value)
  {
  // ## OperationBody [1eb74a04-7420-451d-b616-eabfd777a4a9] 
      dspJNI.USUC_uc_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  // ## OperationBody End 
  }
  
  public SWIGTYPE_p_unsigned_char getUc()
  {
  // ## OperationBody [4bde7694-ed0e-4ad0-9952-daac969a4079] 
      long cPtr = dspJNI.USUC_uc_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  // ## OperationBody End 
  }
  
  public USUC()
  {
  // ## OperationBody [e1391a87-ee59-4892-ac15-46bff0fc8975] 
      this(dspJNI.new_USUC(), true);
  // ## OperationBody End 
  }

}
